### ISSUE TITLE
Topics and Replies not Attached to Forum or Users

### ISSUE THREAD

**Issue by damon18** [damon18/dizkus-bbpress#4]
First successful use of the dizkusZk.php converter brought in all the forums (only one), topics, and replies. But no topics are connected to the forum.

This imported forum only had one forum named General.

It was imported on the test site here.
http://deltasailing.com/wp/forums/
but shows no topics.

Looking at the WP Admin > Topics > All Topics
shows 84 topics listed.
here is a sample topic that was imported.
http://deltasailing.com/wp/forums/topic/dsa-club-racing/

In the Topic Admin List all of the topics are listed as Forum (No Forum), Voices (0), and Author (anonymous), although all of the forum users were imported and assigned to Subscriber status they don't seem linked to any topics or replies.

![delta-test-topics](https://cloud.githubusercontent.com/assets/1587992/14058729/0f473f9c-f2f8-11e5-913a-74993d26e5e9.png)

**Comment by damon18** [comment]
Should add that I did run the "repair forums" tools after doing the import to see if it would help with the above issue. It had no affect.

**Comment by ntwb** [comment]
Did you also import the users at the same time?

If you imported the users from a previous import attempt they won't match up so you should make sure any previously imported users are removed/deleted before importing so the ID's can be mapped correctly during import.

Here's a screenshot of a topic just imported https://cloudup.com/cF5OBDbHIZb
(Ignore those thick black lines, my screen clipping extension is being weird)

A screenshot of the forums before running "repair forums": https://cloudup.com/cFwNGCqT3wK
A screenshot of the forums after  running "repair forums": https://cloudup.com/crTKZbFcMiw

This also was run with the table prefix fix as part of testing #5

**Comment by ntwb** [comment]
Also example topics and replies in the back end: https://cloudup.com/cwqf5GGShIJ https://cloudup.com/cp9KiNOkDIa

**Comment by damon18** [comment]
Your examples all look great. Unfortunately when I tried it all again from scratch I still don't get the users that are imported attributed to any topics or replies.

Doing it from scratch with no users and nothing in bbPress (used the forum reset tool and then deleted users manually)

In the Forum Import tab I entered the required information (first time I entered the prefix but got an sql error) and checked all three boxes.

Import ran completely and users, topics, and replies were imported. But they aren't connected like yours. My test forum is at http://deltasailing.com/wp/forums/

**Comment by damon18** [comment]
Not sure what I'm doing different from you.

**Comment by damon18** [comment]
@ntwb how does dizkusZK.php sense the table prefix?

**Comment by ntwb** [comment]
My, bad, this' fixed using bbPress 2.6-alpha

**Comment by ntwb** [comment]
> @ntwb how does dizkusZK.php sense the table prefix?

bbPress combines all the configuration options for each section and creates a custom MySQL query, when creating that it includes the table prefix added from the importer settings screen and includes it in the custom MySQL query

**Comment by damon18** [comment]
Thanks, I had wondered about that during my failed attempts when it looked like the importer wasn't using the field for the prefix. Thanks for making the prefix configurable. The biggest forum I have to import has over 5,000 topics with about 55,000 replies and it uses the nuke_ prefix instead of zk_ others use other random prefixes that seemed like a good idea at the time of installation.

**Comment by ntwb** [comment]
:+1:
