### ISSUE TITLE
Make Table Prefix Configurable

### ISSUE THREAD

**Issue by damon18** [damon18/dizkus-bbpress#5]
Users of the Dizkus forum on Zikkula have many different prefixes on the tables.

Choosing the prefix for the Zikula tables was part of the installation process for both Postnuke (predecessor of Zikula) and Zikula itself. Choosing a unique prefix was encouraged as a security measure and also to allow sharing one database with more than one install.

Therefore since many installs do not have the zk_ prefix and there is already an allowance in the bbPress 
Tools > Forums > Import Forums > Table Prefix
That is currently used for importing Buddypress forums.

Hopefully this can be activated for this Zikula/Dizkus converter also.

**Comment by ntwb** [comment]
Done

**Comment by damon18** [comment]
Thanks @ntwb
